context:
  env_file: .env
  compose: deploy/docker-compose-template.j2
tasks:
  build:
    - title: all
      pipeline:
        - "docker-compose -f deploy/docker-compose-{ENV}.yml build"
  up:
    - title: all
      pipeline:
        - "docker network create --driver=bridge weather_api_{ENV}"
        - "docker-compose -f deploy/docker-compose-{ENV}.yml up -d"
  down:
    - title: all
      pipeline:
        - "docker-compose -f deploy/docker-compose-{ENV}.yml down"
        - "docker network rm weather_api_{ENV}"
